CREATE TABLE tb_device_credential (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id INTEGER NOT NULL,
    key_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE,
    expires_at TIMESTAMP WITH TIME ZONE,
    current_device_id INTEGER,
    CONSTRAINT fk_device_credential_device FOREIGN KEY (device_id)
        REFERENCES tb_device(id) ON DELETE CASCADE,
    CONSTRAINT uq_device_credential_hash UNIQUE (key_hash),
    CONSTRAINT uq_device_credential_current UNIQUE (current_device_id),
    CONSTRAINT ck_device_credential_current CHECK (
        (revoked_at IS NULL AND current_device_id IS NOT NULL AND current_device_id = device_id)
        OR (revoked_at IS NOT NULL AND current_device_id IS NULL)
    ),
    CONSTRAINT chk_device_credential_hash CHECK (CHAR_LENGTH(key_hash) = 64),
    CONSTRAINT chk_device_credential_expiry CHECK (expires_at IS NULL OR expires_at > created_at),
    CONSTRAINT chk_device_credential_revocation CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);